---
- name: Ejecutar consulta SQL con PowerShell
  win_shell: |
    $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
    $SqlConnection.ConnectionString = "Server={{ mssql_host }},{{ mssql_port }};Database={{db}};User Id={{ mssql_login_user }};Password={{ mssql_login_password }};"
     $SqlCmd = $SqlConnection.CreateCommand()
    $SqlCmd.CommandText = "{{ sql_query }}"
    $SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
    $SqlAdapter.SelectCommand = $SqlCmd
    $DataSet = New-Object System.Data.DataSet
    $SqlAdapter.Fill($DataSet)
    $DataSet.Tables[0] | Format-Table -AutoSize | Out-String
  register: result