---
- name: Bajada de equipos
  microsoft.ad.computer:
    identity: "{{ item }}"
    user: "{{ user_ad }}"
    password: "{{ password_ad }}"
    domain_server: "{{ nombre_ad }}"
    enabled: "{{ estado }}"
  loop: "{{ pc_desabled }}"