---
- name: Bajada de equipos
  community.windows.win_domain_computer:
    name: "{{ item }}"
    dns_hostname: "{{ item }}"  # Agregado: Nombre DNS del equipo
    user: "{{ user_ad }}"
    password: "{{ password_ad }}"
    domain_server: "{{ nombre_ad }}"
    ou: "{{ ou }}"
    enabled: "{{ estado }}"
  loop: "{{ pc_desabled }}"

  
