- name: Desbloquear usuario en Active Directory
  microsoft.ad.user:
    domain_username: "{{ user_ad }}"
    domain_password: "{{ password_ad }}"
    name: "{{ item }}"
    state: present
    enabled: true
  loop: "{{ users_unlock }}"